In [1]:
import pandas as pd

In [10]:
original_df = pd.read_csv("HIVDATA.csv")

In [2]:
df = pd.read_csv("data/hiv_test_1")

In [3]:
df

,QSPRID,Y,Drug
0,A2ARDataset_00009,False,O=[N+]([O-])c1ccccc1SSc1ccccc1[N+](=O)[O-]
1,A2ARDataset_00010,False,CC(C)(CCC(=O)O)CCC(=O)O
2,A2ARDataset_00031,False,CN(C)C1=[S+][Zn-2]2(S1)SC(N(C)C)=[S+]2
3,A2ARDataset_00032,False,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)...
4,A2ARDataset_00033,False,[N-]=[N+]=CC(=O)OCC(N)C(=O)O
...,...,...,...
10086,A2ARDataset_40573,True,CCCCCCCCCCCCCCCC(=O)Nc1ccn(C2CCC(COP(=O)(O)OCC...
10087,A2ARDataset_40574,True,CCCCCCCCCCCCCCCC(=O)Nc1ccn(C2CCC(COP(=O)(O)OCC...
10088,A2ARDataset_40590,False,O=C1C(=Cc2ccc(O)c([N+](=O)[O-])c2)CCCC1=Cc1ccc...
10089,A2ARDataset_40601,False,CC1=C(C(=O)Nc2ccccc2)C2(CCCCC2)C(C#N)=C(SCC(=O...
10090,A2ARDataset_40638,False,Cc1c(C(=O)c2ccccc2)n(COCCCO[Si](C)(C)C(C)(C)C)...

In [4]:
df

,QSPRID,Y,Drug
0,A2ARDataset_00009,False,O=[N+]([O-])c1ccccc1SSc1ccccc1[N+](=O)[O-]
1,A2ARDataset_00010,False,CC(C)(CCC(=O)O)CCC(=O)O
2,A2ARDataset_00031,False,CN(C)C1=[S+][Zn-2]2(S1)SC(N(C)C)=[S+]2
3,A2ARDataset_00032,False,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)...
4,A2ARDataset_00033,False,[N-]=[N+]=CC(=O)OCC(N)C(=O)O
...,...,...,...
10086,A2ARDataset_40573,True,CCCCCCCCCCCCCCCC(=O)Nc1ccn(C2CCC(COP(=O)(O)OCC...
10087,A2ARDataset_40574,True,CCCCCCCCCCCCCCCC(=O)Nc1ccn(C2CCC(COP(=O)(O)OCC...
10088,A2ARDataset_40590,False,O=C1C(=Cc2ccc(O)c([N+](=O)[O-])c2)CCCC1=Cc1ccc...
10089,A2ARDataset_40601,False,CC1=C(C(=O)Nc2ccccc2)C2(CCCCC2)C(C#N)=C(SCC(=O...
10090,A2ARDataset_40638,False,Cc1c(C(=O)c2ccccc2)n(COCCCO[Si](C)(C)C(C)(C)C)...

In [5]:
def extract_id_from_string(text):
    str_text = str(text)
    int_id = int(str_text.split('_')[-1])
    return int_id
indexes_to_remove=[71, 20031, 17054, 28867, 29078, 28112, 25117, 33252, 39561, 39293, 40500, 39604, 40510, 39894, 23457, 1883, 1848, 450, 10499, 5476, 6679, 20046, 14769, 5950, 12216, 22430, 22426, 9034, 9876, 2202, 27142, 1299, 1805, 29622, 25009, 29646, 9218, 17673, 10325, 31053, 24736, 12815, 20952, 27910, 23716, 7245, 1968, 14653, 26318, 25042, 22425, 22432, 2060, 20957, 21664, 8818, 20383, 33539, 5452, 24667, 24674, 4947, 34815, 24611, 11048, 1141, 19526, 11095, 20645, 1973, 4607, 32554, 14255, 13193, 3, 1395, 8835, 6438, 27908, 22703, 27907, 6407, 30873, 23053, 13838, 30935, 13839, 22295, 15075, 1301, 22305, 1300, 26808, 35183, 15033, 16141, 17807, 22785, 11843, 4692, 28596, 14250, 8742, 17059, 23086]

In [46]:
for i in range(1, 11):
    X1 = pd.read_csv(f"data/hiv_train_{i}")
    X2 = pd.read_csv(f"data/hiv_val_{i}")
    X3 = pd.read_csv(f"data/hiv_test_{i}")
    
    print(X1.shape)
    X1["ID"] = X1["QSPRID"].apply(extract_id_from_string)
    X1 = X1[~X1["ID"].isin(indexes_to_remove)] 
    y1= X1.Y
    print(X1.shape)
    
    print(X2.shape)
    X2["ID"] = X2["QSPRID"].apply(extract_id_from_string)
    X2 = X2[~X2["ID"].isin(indexes_to_remove)] 
    y2= X2.Y
    print(X2.shape)
    
    print(X3.shape)
    X3["ID"] = X3["QSPRID"].apply(extract_id_from_string)
    X3 = X3[~X3["ID"].isin(indexes_to_remove)]
    y3= X3.Y
    print(X3.shape)
    
    y1.to_csv(f"mod_data/y1.{i}")
    y2.to_csv(f"mod_data/y2.{i}")
    y3.to_csv(f"mod_data/y3.{i}")
    
    X1 = original_df[original_df.QSPRID.isin(X1.QSPRID)]
    X2 = original_df[original_df.QSPRID.isin(X2.QSPRID)]
    X3 = original_df[original_df.QSPRID.isin(X3.QSPRID)]
    
    X1.drop("Y", axis=1).to_csv(f"mod_data/X1.{i}")
    X2.drop("Y", axis=1).to_csv(f"mod_data/X2.{i}")
    X3.drop("Y", axis=1).to_csv(f"mod_data/X3.{i}")

(21728, 3)
(21671, 4)
(8851, 3)
(8830, 4)
(10091, 3)
(10064, 4)
(22200, 3)
(22127, 4)
(8664, 3)
(8644, 4)
(9806, 3)
(9794, 4)
(22060, 3)
(21991, 4)
(8919, 3)
(8903, 4)
(9691, 3)
(9671, 4)
(22279, 3)
(22232, 4)
(8852, 3)
(8818, 4)
(9539, 3)
(9515, 4)
(22222, 3)
(22148, 4)
(8831, 3)
(8815, 4)
(9617, 3)
(9602, 4)
(22225, 3)
(22173, 4)
(8795, 3)
(8771, 4)
(9650, 3)
(9621, 4)
(21536, 3)
(21471, 4)
(9117, 3)
(9104, 4)
(10017, 3)
(9990, 4)
(22289, 3)
(22225, 4)
(8848, 3)
(8826, 4)
(9533, 3)
(9514, 4)
(6976, 3)
(6938, 4)
(10995, 3)
(10972, 4)
(22699, 3)
(22655, 4)
(6638, 3)
(6608, 4)
(11630, 3)
(11606, 4)
(22402, 3)
(22351, 4)

In [44]:

lol = original_df[original_df.QSPRID.isin(X1.QSPRID)]

In [37]:
display(lol.shape)

(21671, 4727)

In [36]:
display(y1)

0        False
1        False
3        False
4        False
5        False
         ...
21723    False
21724    False
21725    False
21726    False
21727    False
Name: Y, Length: 21671, dtype: bool

In [39]:
for i in range(lol.shape[0]):
    if y1.iloc[i] != lol.Y.iloc[i]:
        print("chyba")
print("Hotovo")

Hotovo

In [40]:
display(pd.read_csv("mod_data/X1.1"))

,QSPRID,300,301,302,303,304,305,306,307,308,...,RDkit_fr_sulfonamd,RDkit_fr_sulfone,RDkit_fr_term_acetylene,RDkit_fr_tetrazole,RDkit_fr_thiazole,RDkit_fr_thiocyan,RDkit_fr_thiophene,RDkit_fr_unbrch_alkane,RDkit_fr_urea,RDkit_qed
0,A2ARDataset_00000,0.856747,1.271848,0.477435,-0.832384,-0.801132,-0.988249,0.653618,0.065282,0.193137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.434358
1,A2ARDataset_00001,0.452506,0.462552,-0.210664,-0.215571,0.515784,-0.152794,0.825898,-0.038565,0.136324,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.581359
2,A2ARDataset_00002,-0.710739,0.348930,0.437538,-0.138845,0.188291,-0.577048,0.447970,0.189413,0.070475,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.357615
3,A2ARDataset_00003,-0.730703,-0.058071,1.191474,-0.659712,0.153476,-0.437317,0.504877,-0.000563,-0.425432,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538723
4,A2ARDataset_00004,-0.257824,1.094919,0.423548,-0.139947,-0.083240,-0.741900,0.448479,0.183446,0.290794,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.790087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21723,A2ARDataset_21723,-0.130388,0.772013,0.152538,-0.037299,0.077947,-1.051099,0.573175,-0.003305,0.520750,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.804191
21724,A2ARDataset_21724,-0.029268,1.207125,0.066604,0.123513,0.018418,-1.239438,0.663889,-0.017742,0.653052,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.427745
21725,A2ARDataset_21725,-0.081206,0.809170,-0.035853,0.158540,0.031100,-0.842095,0.343086,0.131871,0.488234,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
21726,A2ARDataset_21726,-0.067375,0.829996,0.012404,0.147336,0.063484,-0.860034,0.361485,0.128738,0.416006,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
21727,A2ARDataset_21727,-0.453452,0.775580,-0.016286,0.156739,-0.304492,-1.139458,0.571841,0.143984,0.508280,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.187492

In [41]:
display(lol.drop("Y", axis=1))

,QSPRID,300,301,302,303,304,305,306,307,308,...,RDkit_fr_sulfonamd,RDkit_fr_sulfone,RDkit_fr_term_acetylene,RDkit_fr_tetrazole,RDkit_fr_thiazole,RDkit_fr_thiocyan,RDkit_fr_thiophene,RDkit_fr_unbrch_alkane,RDkit_fr_urea,RDkit_qed
0,A2ARDataset_00000,0.856747,1.271848,0.477435,-0.832384,-0.801132,-0.988249,0.653618,0.065282,0.193137,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.434358
2,A2ARDataset_00002,0.452506,0.462552,-0.210664,-0.215571,0.515784,-0.152794,0.825898,-0.038565,0.136324,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.581359
4,A2ARDataset_00004,-0.730703,-0.058071,1.191474,-0.659712,0.153476,-0.437317,0.504877,-0.000563,-0.425432,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538723
5,A2ARDataset_00005,-0.257824,1.094919,0.423548,-0.139947,-0.083240,-0.741900,0.448479,0.183446,0.290794,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.790087
6,A2ARDataset_00006,-0.276051,0.748681,0.543313,-0.488788,0.342708,0.050164,0.174454,-0.701084,-0.018162,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.610259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40665,A2ARDataset_40665,-0.130388,0.772013,0.152538,-0.037299,0.077947,-1.051099,0.573175,-0.003305,0.520750,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.804191
40666,A2ARDataset_40666,-0.029268,1.207125,0.066604,0.123513,0.018418,-1.239438,0.663889,-0.017742,0.653052,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.427745
40667,A2ARDataset_40667,-0.081206,0.809170,-0.035853,0.158540,0.031100,-0.842095,0.343086,0.131871,0.488234,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
40668,A2ARDataset_40668,-0.067375,0.829996,0.012404,0.147336,0.063484,-0.860034,0.361485,0.128738,0.416006,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
40669,A2ARDataset_40669,-0.453452,0.775580,-0.016286,0.156739,-0.304492,-1.139458,0.571841,0.143984,0.508280,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.187492

In [42]:
display(lol)

,QSPRID,Y,300,301,302,303,304,305,306,307,...,RDkit_fr_sulfonamd,RDkit_fr_sulfone,RDkit_fr_term_acetylene,RDkit_fr_tetrazole,RDkit_fr_thiazole,RDkit_fr_thiocyan,RDkit_fr_thiophene,RDkit_fr_unbrch_alkane,RDkit_fr_urea,RDkit_qed
0,A2ARDataset_00000,False,0.856747,1.271848,0.477435,-0.832384,-0.801132,-0.988249,0.653618,0.065282,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.434358
2,A2ARDataset_00002,False,0.452506,0.462552,-0.210664,-0.215571,0.515784,-0.152794,0.825898,-0.038565,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.581359
4,A2ARDataset_00004,False,-0.730703,-0.058071,1.191474,-0.659712,0.153476,-0.437317,0.504877,-0.000563,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.538723
5,A2ARDataset_00005,False,-0.257824,1.094919,0.423548,-0.139947,-0.083240,-0.741900,0.448479,0.183446,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.790087
6,A2ARDataset_00006,False,-0.276051,0.748681,0.543313,-0.488788,0.342708,0.050164,0.174454,-0.701084,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.610259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40665,A2ARDataset_40665,False,-0.130388,0.772013,0.152538,-0.037299,0.077947,-1.051099,0.573175,-0.003305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.804191
40666,A2ARDataset_40666,False,-0.029268,1.207125,0.066604,0.123513,0.018418,-1.239438,0.663889,-0.017742,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.427745
40667,A2ARDataset_40667,False,-0.081206,0.809170,-0.035853,0.158540,0.031100,-0.842095,0.343086,0.131871,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
40668,A2ARDataset_40668,False,-0.067375,0.829996,0.012404,0.147336,0.063484,-0.860034,0.361485,0.128738,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.450949
40669,A2ARDataset_40669,False,-0.453452,0.775580,-0.016286,0.156739,-0.304492,-1.139458,0.571841,0.143984,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.187492