In [1]:
import os
import qsprpred

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.sampling.splits import GBMTDataSplit

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [3]:
os.makedirs("dataset_outputs/hERG/data", exist_ok=True)

# Create dataset
dataset_test = QSPRDataset.fromTableFile(
    filename="data/src/datasets/a2ar/data/A2AR.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
)

In [4]:
dataset_test.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset_test),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
)

In [5]:
display(dataset_test.X_ind.index)

Index(['A2ARDataset_0002', 'A2ARDataset_0005', 'A2ARDataset_0006',
       'A2ARDataset_0008', 'A2ARDataset_0010', 'A2ARDataset_0019',
       'A2ARDataset_0023', 'A2ARDataset_0025', 'A2ARDataset_0026',
       'A2ARDataset_0041',
       ...
       'A2ARDataset_4041', 'A2ARDataset_4047', 'A2ARDataset_4053',
       'A2ARDataset_4058', 'A2ARDataset_4059', 'A2ARDataset_4063',
       'A2ARDataset_4068', 'A2ARDataset_4075', 'A2ARDataset_4079',
       'A2ARDataset_4080'],
      dtype='object', name='QSPRID', length=860)

In [6]:
display(dataset_test.getDF().QSPRID)

QSPRID
A2ARDataset_0000    A2ARDataset_0000
A2ARDataset_0001    A2ARDataset_0001
A2ARDataset_0002    A2ARDataset_0002
A2ARDataset_0003    A2ARDataset_0003
A2ARDataset_0004    A2ARDataset_0004
                          ...
A2ARDataset_4077    A2ARDataset_4077
A2ARDataset_4078    A2ARDataset_4078
A2ARDataset_4079    A2ARDataset_4079
A2ARDataset_4080    A2ARDataset_4080
A2ARDataset_4081    A2ARDataset_4081
Name: QSPRID, Length: 4082, dtype: object

In [7]:
dataset_1 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/a2ar/data/A2AR.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41,
    smiles_col = 'Drug',
    sep=','
)

In [8]:
    dataset_1.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset_test),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )

In [9]:
dataset_1.getDF().loc[dataset_1.getDF().index.isin(dataset_1.X_ind.index)][["Y", "Drug"]]

                      Y                                               Drug
QSPRID
A2ARDataset_0002   True   O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1
A2ARDataset_0006   True                Nc1nc(-c2ccccc2)cn2cc(-c3ccco3)nc12
A2ARDataset_0007   True  CCCn1c(=O)c2c(nc3n2CCCN3c2ccc(OCCN3CCCC3)cc2)n...
A2ARDataset_0008   True                  N#Cc1c(-c2ccccc2)cc(-c2ccco2)nc1N
A2ARDataset_0010  False            COc1nc(N)c(C#N)c(-c2ccc3c(c2)OCO3)c1C#N
...                 ...                                                ...
A2ARDataset_4063   True                   Cc1cc(O)c(C(C)C)cc1N=C1CSC(=O)N1
A2ARDataset_4064   True    CCOC(=O)c1nc(NC(=O)c2ccc(F)cc2)nc2nn(C(C)C)cc12
A2ARDataset_4067   True     Fc1ccc(CNc2nc(-c3ccc(Cl)cc3)cc(C(F)(F)F)n2)cc1
A2ARDataset_4070   True  CCCCn1c(=O)c2c(nc3n2CCCN3c2ccc(OCCN3CCCC3)cc2)...
A2ARDataset_4079  False              Nc1nc(CSc2nnc(N)s2)nc(Nc2ccc(F)cc2)n1

[883 rows x 2 columns]

In [10]:
dataset_1.df

,Y,Drug,QSPRID,Y_original
QSPRID,,,,
A2ARDataset_0000,True,Cc1cc(C)n(-c2cc(NC(=O)CCN(C)C)nc(-c3ccc(C)o3)n...,A2ARDataset_0000,1
A2ARDataset_0001,False,Nc1c(C(=O)Nc2ccc([N+](=O)[O-])cc2)sc2nc3c(cc12...,A2ARDataset_0001,0
A2ARDataset_0002,True,O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1,A2ARDataset_0002,1
A2ARDataset_0003,True,CNC(=O)C12CC1C(n1cnc3c(NCc4cccc(Cl)c4)nc(C#CCC...,A2ARDataset_0003,1
A2ARDataset_0004,True,CCCn1c(=O)c2c(nc3cc(OC)ccn32)n(CCCNC(=O)c2ccc(...,A2ARDataset_0004,1
...,...,...,...,...
A2ARDataset_4077,True,CNc1ncc(C(=O)NCc2ccc(OC)cc2)c2nc(-c3ccco3)nn12,A2ARDataset_4077,1
A2ARDataset_4078,True,Nc1nc(-c2ccco2)c2ncn(C(=O)NCCc3ccccc3)c2n1,A2ARDataset_4078,1
A2ARDataset_4079,False,Nc1nc(CSc2nnc(N)s2)nc(Nc2ccc(F)cc2)n1,A2ARDataset_4079,0
A2ARDataset_4080,True,CCCOc1ccc(C=Cc2cc3c(c(=O)n(C)c(=O)n3C)n2C)cc1,A2ARDataset_4080,1
A2ARDataset_4081,True,CCOC(=O)c1cnc(NCC(C)C)n2nc(-c3ccco3)nc12,A2ARDataset_4081,1

In [11]:
    dataset_1.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset_test),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )

In [12]:
dataset_1.getDF().index

Index(['A2ARDataset_0000', 'A2ARDataset_0001', 'A2ARDataset_0002',
       'A2ARDataset_0003', 'A2ARDataset_0004', 'A2ARDataset_0005',
       'A2ARDataset_0006', 'A2ARDataset_0007', 'A2ARDataset_0008',
       'A2ARDataset_0009',
       ...
       'A2ARDataset_4072', 'A2ARDataset_4073', 'A2ARDataset_4074',
       'A2ARDataset_4075', 'A2ARDataset_4076', 'A2ARDataset_4077',
       'A2ARDataset_4078', 'A2ARDataset_4079', 'A2ARDataset_4080',
       'A2ARDataset_4081'],
      dtype='object', name='QSPRID', length=4082)

In [13]:
dataset_1.X_ind.index

Index(['A2ARDataset_0001', 'A2ARDataset_0002', 'A2ARDataset_0005',
       'A2ARDataset_0006', 'A2ARDataset_0008', 'A2ARDataset_0012',
       'A2ARDataset_0018', 'A2ARDataset_0025', 'A2ARDataset_0026',
       'A2ARDataset_0037',
       ...
       'A2ARDataset_4036', 'A2ARDataset_4039', 'A2ARDataset_4055',
       'A2ARDataset_4057', 'A2ARDataset_4058', 'A2ARDataset_4059',
       'A2ARDataset_4062', 'A2ARDataset_4063', 'A2ARDataset_4066',
       'A2ARDataset_4067'],
      dtype='object', name='QSPRID', length=873)

In [2]:
os.makedirs("A2AR/data", exist_ok=True)
ind = 0
for i in range(1,11):
    dataset = QSPRDataset.fromTableFile(
    filename="data/src/datasets/a2ar/data/A2AR.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    dataset2 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/a2ar/data/A2AR.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset2.df = dataset.getDF().loc[~dataset.getDF().index.isin(dataset.X_ind.index)].copy()
    dataset2.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.25, dataset=dataset2),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    
    df_test = dataset.getDF().loc[dataset.getDF().index.isin(dataset.X_ind.index)][["Y", "Drug"]]
    df_train = dataset2.getDF().loc[~dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]
    df_val = dataset2.getDF().loc[dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]

    print(i)
    print(df_train.shape)
    print(df_val.shape)
    print(df_test.shape)
    df_train.to_csv(f"A2AR/data/a2ar_train_{i}")
    df_val.to_csv(f"A2AR/data/a2ar_val_{i}")
    df_test.to_csv(f"A2AR/data/a2ar_test_{i}")

1
(2407, 2)
(811, 2)
(864, 2)
2
(2408, 2)
(796, 2)
(878, 2)
3
(2408, 2)
(802, 2)
(872, 2)
4
(2411, 2)
(787, 2)
(884, 2)
5
(2432, 2)
(781, 2)
(869, 2)
6
(2427, 2)
(783, 2)
(872, 2)
7
(2423, 2)
(794, 2)
(865, 2)
8
(2400, 2)
(800, 2)
(882, 2)
9
(2390, 2)
(814, 2)
(878, 2)
10
(2398, 2)
(783, 2)
(901, 2)

In [3]:
os.makedirs("A2AR/data", exist_ok=True)
ind = 0
for i in range(1,11):
    dataset = QSPRDataset.fromTableFile(
    filename="data/src/datasets/ck1/data/CK1.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    dataset2 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/ck1/data/CK1.csv",
    store_dir="dataset_outputs/ck1/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset2.df = dataset.getDF().loc[~dataset.getDF().index.isin(dataset.X_ind.index)].copy()
    dataset2.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.25, dataset=dataset2),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    
    df_test = dataset.getDF().loc[dataset.getDF().index.isin(dataset.X_ind.index)][["Y", "Drug"]]
    df_train = dataset2.getDF().loc[~dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]
    df_val = dataset2.getDF().loc[dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]

    print(i)
    print(df_train.shape)
    print(df_val.shape)
    print(df_test.shape)
    df_train.to_csv(f"CK1/data/ck1_train_{i}")
    df_val.to_csv(f"CK1/data/ck1_val_{i}")
    df_test.to_csv(f"CK1/data/ck1_test_{i}")

1
(488, 2)
(155, 2)
(164, 2)
2
(488, 2)
(155, 2)
(164, 2)
3
(490, 2)
(155, 2)
(162, 2)
4
(492, 2)
(155, 2)
(160, 2)
5
(488, 2)
(155, 2)
(164, 2)
6
(492, 2)
(156, 2)
(159, 2)
7
(495, 2)
(156, 2)
(156, 2)
8
(493, 2)
(155, 2)
(159, 2)
9
(491, 2)
(155, 2)
(161, 2)
10
(489, 2)
(156, 2)
(162, 2)

In [2]:
os.makedirs("A2AR/data", exist_ok=True)
ind = 0
for i in range(1,11):
    dataset = QSPRDataset.fromTableFile(
    filename="data/src/datasets/herg_large/data/hERG_large.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    dataset2 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/herg_large/data/hERG_large.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset2.df = dataset.getDF().loc[~dataset.getDF().index.isin(dataset.X_ind.index)].copy()
    dataset2.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.25, dataset=dataset2),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    
    df_test = dataset.getDF().loc[dataset.getDF().index.isin(dataset.X_ind.index)][["Y", "Drug"]]
    df_train = dataset2.getDF().loc[~dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]
    df_val = dataset2.getDF().loc[dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]

    print(i)
    print(df_train.shape)
    print(df_val.shape)
    print(df_test.shape)
    df_train.to_csv(f"hERG/data/herg_train_{i}")
    df_val.to_csv(f"hERG/data/herg_val_{i}")
    df_test.to_csv(f"hERG/data/herg_test_{i}")

1
(7856, 2)
(3133, 2)
(3333, 2)
2
(7804, 2)
(3192, 2)
(3326, 2)
3
(7787, 2)
(3149, 2)
(3386, 2)
4
(7766, 2)
(3199, 2)
(3357, 2)
5
(7781, 2)
(3178, 2)
(3363, 2)
6
(7715, 2)
(3166, 2)
(3441, 2)
7
(7808, 2)
(3128, 2)
(3386, 2)
8
(7798, 2)
(3157, 2)
(3367, 2)
9
(7821, 2)
(3140, 2)
(3361, 2)
10
(7852, 2)
(3114, 2)
(3356, 2)

In [2]:
os.makedirs("A2AR/data", exist_ok=True)
ind = 0
for i in range(9,11):
    dataset = QSPRDataset.fromTableFile(
    filename="data/src/datasets/hiv/data/HIV.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    dataset2 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/hiv/data/HIV.csv",
    store_dir="dataset_outputs/a2ar/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41+i,
    smiles_col = 'Drug',
    sep=','
    )
    dataset2.df = dataset.getDF().loc[~dataset.getDF().index.isin(dataset.X_ind.index)].copy()
    dataset2.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.25, dataset=dataset2),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )
    
    df_test = dataset.getDF().loc[dataset.getDF().index.isin(dataset.X_ind.index)][["Y", "Drug"]]
    df_train = dataset2.getDF().loc[~dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]
    df_val = dataset2.getDF().loc[dataset2.getDF().index.isin(dataset2.X_ind.index)][["Y", "Drug"]]

    print(i)
    print(df_train.shape)
    print(df_val.shape)
    print(df_test.shape)
    df_train.to_csv(f"HIV/data/hiv_train_{i}")
    df_val.to_csv(f"HIV/data/hiv_val_{i}")
    df_test.to_csv(f"HIV/data/hiv_test_{i}")

9
(6976, 2)
(10995, 2)
(22699, 2)
10
(6638, 2)
(11630, 2)
(22402, 2)

In [14]:
herg_test = dataset_test.df[dataset_test.df.index.isin(dataset_test.X_ind.index)]
herg_test.to_csv(f"A2AR/data/a2ar_test")

In [ ]:
from qsprpred.data.descriptors.sets import RDKitDescs

rdkit_descs = RDKitDescs()

dataset.addDescriptors([rdkit_descs])

dataset.descriptorSets

In [ ]:
import torch
from transformers import RobertaTokenizerFast, RobertaForMaskedLM, DataCollatorWithPadding
from torch.utils.data import DataLoader, Dataset

# Nastavení zařízení (GPU nebo CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Načtení tokenizeru a modelu
tokenizer = RobertaTokenizerFast.from_pretrained("entropy/roberta_zinc_480m", max_len=128)
model = RobertaForMaskedLM.from_pretrained('entropy/roberta_zinc_480m')

# Přenesení modelu na správné zařízení
model.to(device)

# Připravení collatoru pro padding
collator = DataCollatorWithPadding(tokenizer, padding=True, return_tensors='pt')

# Načtení seznamu SMILES (například z nějaké jiné struktury než datasetu)
smiles = ["CCO", "CC(=O)O", "CCN", "CC(C)O", "CCC", "CCCC", "CCCO"] * 100  # Příklad seznamu SMILES, můžeš použít vlastní

# Vytvoření datasetu
smiles_dataset = SMILESDataset(smiles, tokenizer)

# Vytvoření DataLoaderu (dávky po 32)
batch_size = 32
dataloader = DataLoader(smiles_dataset, batch_size=batch_size, collate_fn=collator)

# Zpracování dat po dávkách
model.eval()  # Převede model do evaluačního režimu (bez trénování)
embeddings_list = []  # Uchováme všechny embeddings

with torch.no_grad():  # Nevytvářet gradienty během evaluace
    for batch in dataloader:
        # Zkontroluj tvar batchů
        print("Batch input_ids tvar:", batch['input_ids'].shape)
        print("Batch attention_mask tvar:", batch['attention_mask'].shape)

        # Přenesení všech vstupů na správné zařízení (GPU nebo CPU)
        input_ids = batch['input_ids'].squeeze(1).to(device)  # Squeeze odstraní extra dimenzi
        attention_mask = batch['attention_mask'].squeeze(1).to(device)  # Squeeze odstraní extra dimenzi

        # Modelování výstupů s hidden states
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)

        # Získání poslední vrstvy hidden states
        full_embeddings = outputs[1][-1]

        # Výpočet průměrného embeddingu pro každý token
        embeddings = ((full_embeddings * attention_mask.unsqueeze(-1)).sum(1) / attention_mask.sum(-1).unsqueeze(-1))
        
        # Uložení embeddings pro tuto dávku
        embeddings_list.append(embeddings)

# Spojení všech embeddings z dávky do jednoho tensoru
all_embeddings = torch.cat(embeddings_list, dim=0)

# Teď můžeš použít `all_embeddings`, což obsahuje embeddings pro všechny SMILES v datasetu