In [1]:
import os
import qsprpred
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.descriptors.sets import RDKitDescs
from MolEval import MolEmb

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'

In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from qsprpred.data.descriptors.sets import RDKitDescs

def load_datasets(path):
    dataset = QSPRDataset.fromTableFile(
    filename=path,
    store_dir="dataset_outputs/A2AR/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
    )
    #dataset.prepareDataset(
    #feature_calculators=[MorganFP(radius=2, nBits=1024)],
    #recalculate_features=True,
    #shuffle=False
    #)
    #from qsprpred.data.descriptors.sets import RDKitDescs
    
    #rdkit_descs = RDKitDescs()
    
    #dataset.addDescriptors([rdkit_descs])
    
    #dataset.descriptorSets
    return dataset

class Dataset_creator():
    def __init__(self, model_names=['RoBERTa_ZINC'], corr_thrsh= 0.95):
        self.variance = VarianceThreshold(threshold=0.0)
        self.model_names = model_names
        self.corr_thrsh = corr_thrsh
        self.selected_indices = None
        
    def fit_transform(self, dataset):
        dataset.prepareDataset(feature_calculators=[MorganFP(radius=2, nBits=4096)], recalculate_features=True, shuffle=False)
        rdkit_descs = RDKitDescs()
        dataset.addDescriptors([rdkit_descs])
        display(dataset.X.shape)
        
        dataset.descriptorSets
        dataset_embs = self.create_embs(dataset)
        dataset_embs.index = dataset.X.index
        dataset.X = pd.concat([dataset.X, dataset_embs], axis=1)
        display(dataset.X.shape)
        
        dataset_no_var_np = self.variance.fit_transform(dataset.X)
        mask = self.variance.get_support()
        dataset_without_no_var = pd.DataFrame(
            dataset_no_var_np,
            columns=dataset.X.columns[mask],
            index=dataset.X.index)
        display(dataset_without_no_var.shape)

        
        dataset_without_high_corr = self.high_correlation(dataset_without_no_var)
        display(dataset_without_high_corr.shape)
        
        dataset.X = dataset_without_high_corr
        return dataset
        
    def transform(self, dataset):
        dataset.prepareDataset(feature_calculators=[MorganFP(radius=2, nBits=4096)], recalculate_features=True, shuffle=False)
        rdkit_descs = RDKitDescs()
        dataset.addDescriptors([rdkit_descs])
        display(dataset.X.shape)

        dataset.descriptorSets
        dataset_embs = self.create_embs(dataset)
        dataset_embs.index = dataset.X.index
        dataset.X = pd.concat([dataset.X, dataset_embs], axis=1)
        display(dataset.X.shape)

        dataset_no_var_np = self.variance.transform(dataset.X)
        mask = self.variance.get_support()
        dataset_without_no_var = pd.DataFrame(
            dataset_no_var_np,
            columns=dataset.X.columns[mask],
            index=dataset.X.index)
        display(dataset_without_no_var.shape)

        dataset_without_high_corr = dataset_without_no_var[self.selected_indices]
        display(dataset_without_high_corr.shape)

        dataset.X = dataset_without_high_corr
        return dataset

    def high_correlation(self, df: pd.DataFrame):
        corr_matrix = df.corr().abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        
        to_drop = [column for column in upper.columns if any(upper[column] > self.corr_thrsh)]
        self.selected_indices = df.columns.difference(to_drop)
        
        return df[self.selected_indices]

        
    def create_embs(self, dataset):
        dataset.df["SMILES"] = dataset.df["Drug"]
        final_emb = pd.DataFrame()
        for model_name in self.model_names:
            extractor = MolEmb.EmbeddingExtractor(model_name=model_name, df=dataset.df)
            new_emb, dataset.df = extractor.get_embeddings()
            display(type(new_emb))
            if final_emb.empty:
                final_emb = new_emb
            else:
                final_emb = pd.concat([final_emb, new_emb], axis=1)
        final_emb.columns = final_emb.columns.astype(str)
        display(final_emb)
        return final_emb

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X1_all = load_datasets("HIV/data/hiv_train_1")

X2_all = load_datasets("HIV/data/hiv_val_1")

X3_all = load_datasets("HIV/data/hiv_test_1")

In [4]:
cls = Dataset_creator(['Mol2Vec', 'RoBERTa_ZINC'])

In [ ]:
X1_all = cls.fit_transform(X1_all)
X2_all = cls.transform(X2_all)
X3_all = cls.transform(X3_all)

In [ ]:
for i in range(2, 11):
    X1_all = load_datasets(f"HIV/data/hiv_train_{i}")

    X2_all = load_datasets(f"HIV/data/hiv_val_{i}")

    X3_all = load_datasets(f"HIV/data/hiv_test_{i}")
    cls = Dataset_creator(['Mol2Vec', 'RoBERTa_ZINC'])
    X1_all = cls.fit_transform(X1_all)
    X2_all = cls.transform(X2_all)
    X3_all = cls.transform(X3_all)

    X1_all.X.to_csv(f"HIV/mod_data/X1.{i}")
    X2_all.X.to_csv(f"HIV/mod_data/X2.{i}")
    X3_all.X.to_csv(f"HIV/mod_data/X3.{i}")
    X1_all.y.to_csv(f"HIV/mod_data/y1.{i}")
    X2_all.y.to_csv(f"HIV/mod_data/y2.{i}")
    X3_all.y.to_csv(f"HIV/mod_data/y3.{i}")

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

(22200, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,1.830049,5.304307,-2.638319,3.339625,2.323060,1.235785,-12.138524,2.645428,1.863030,3.719823,...,0.334936,-0.000670,-0.489490,-0.193004,0.183476,-0.707753,0.371550,0.815464,0.102897,-1.178634
1,1.833409,1.726148,-7.006849,14.767018,-1.094783,-1.150211,-22.999550,3.627929,12.653315,13.545957,...,-0.240150,-0.279489,-0.493433,-0.276344,-0.203011,-0.674934,0.216598,0.562075,0.107855,-1.521570
2,2.331327,-0.651370,-6.820276,4.460179,2.888736,2.596256,-10.667131,1.601155,7.585736,9.250560,...,0.202170,-0.505404,-0.373032,0.096098,0.439506,0.026940,1.228032,-0.038164,-0.153394,-0.561331
3,1.245269,-2.941263,-0.752463,-0.470454,1.706033,1.063615,-3.766093,2.574552,3.772649,3.572893,...,-0.520831,-0.523918,-0.366259,0.264228,-0.055211,0.905929,0.355022,0.138676,-0.471907,-0.046056
4,1.517411,-0.614370,-0.137746,8.954222,-0.948801,-0.775231,-6.088184,-2.620385,8.403460,1.148298,...,-0.107419,0.451694,0.135411,-0.111082,-0.193958,-0.098032,0.528591,-0.554009,-0.036641,-0.323031
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22195,3.621877,-2.954766,-1.634619,6.354789,-0.681765,1.790700,-12.516966,1.306191,4.478281,5.584552,...,0.416588,0.082800,-0.307322,0.166654,0.157321,0.123480,0.374305,-0.284418,-0.168759,-0.555168
22196,-3.572031,-8.533897,-8.402864,3.071481,3.880468,-9.588969,-27.329983,2.626203,9.648467,-2.330538,...,0.033101,-0.246923,-0.589911,-0.175303,0.068958,-0.229805,0.959378,0.208976,-0.007658,-1.159689
22197,-4.151707,-3.119363,-6.816376,4.004745,7.243800,-4.586811,-42.958820,4.693540,17.874502,6.278709,...,0.289923,-0.229027,-0.886972,0.302299,0.182994,0.017574,0.837775,0.695176,-0.436155,-1.424014
22198,-4.559140,-2.542769,-6.259412,-1.744846,8.704000,-3.398432,-17.737125,-2.524212,5.417196,-7.001977,...,-0.551723,-0.279244,0.073502,0.026926,0.548097,-0.014771,0.571225,0.100328,-0.030059,-0.625115
22199,-4.944569,-3.410291,-7.430757,1.254209,7.476906,-1.584275,-21.781797,-1.663402,6.743775,-5.239288,...,-0.515869,-0.074915,-0.044484,0.021765,0.342564,-0.182944,0.385058,0.284613,-0.098328,-0.641787

(22200, 5374)

(22200, 5370)

(22200, 4722)

(8664, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.456545,0.275523,-1.782677,1.315240,-0.304189,0.188262,-5.266070,0.162359,2.533442,2.168227,...,-1.080665,0.101773,-0.634371,-0.003949,-0.077092,0.479205,1.080722,0.224690,-0.334254,-0.230768
1,1.062619,-2.765399,-5.391538,8.944172,2.002307,0.962824,-13.621710,0.141490,8.604310,3.867580,...,0.193403,-0.048743,-0.165164,-0.393784,0.349663,-0.158135,1.142828,-0.407274,0.205548,-0.899578
2,-0.235595,-2.453207,-1.609678,5.308835,-0.765441,-1.808747,-6.565049,0.907175,5.192681,3.059043,...,0.127270,0.205279,-0.043492,-0.520117,0.427229,-0.708847,0.648929,-0.137198,0.244726,-0.379504
3,-0.172001,-1.593874,-1.158574,-0.354243,2.400865,0.363590,-3.115545,0.710441,4.033671,-0.266197,...,-0.663936,-0.647461,-0.898023,-0.154735,0.240776,0.859579,0.666328,-0.216713,0.128265,-0.123865
4,-1.179480,-0.472077,2.418220,3.237857,2.062965,-0.443165,-8.465720,-4.719286,6.842691,-2.259923,...,0.720784,-0.771542,-0.106494,-0.135193,-0.148940,-0.074640,-0.160576,0.278002,-0.171108,0.060323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8659,2.608390,-6.096492,-1.043300,4.551602,-1.026818,-4.465841,-10.286528,0.344521,2.538278,1.096367,...,-0.147331,0.159386,-0.400167,0.104859,0.473699,-0.271323,1.160659,0.116244,-0.126652,-1.094522
8660,2.587630,-7.165244,-3.397100,5.840809,-1.007105,-6.378576,-13.567078,-0.032094,5.083066,4.404552,...,-0.135657,0.038241,-0.406587,-0.023539,-0.090389,-0.327237,0.901141,0.387756,0.015935,-1.436082
8661,2.172952,-6.267159,-2.897906,6.958421,-0.721393,-7.033988,-13.599429,-0.071477,6.933540,5.233133,...,-0.215621,0.229343,-0.453490,0.342950,0.037996,-0.143402,0.679552,0.520276,0.028721,-1.412053
8662,2.144235,-6.164550,-2.714616,7.038599,-0.714388,-6.902690,-13.486728,0.139255,6.704244,5.088447,...,-0.319623,0.211111,-0.489075,0.331771,-0.010457,-0.149293,0.686197,0.433241,0.072223,-1.400403
8663,0.006827,-6.562754,-6.269722,11.268374,3.681344,3.841276,-15.926844,-2.676855,5.721858,-1.735141,...,0.231330,0.028582,-0.611265,-0.299666,0.015596,0.265076,0.833399,-0.454563,-0.049352,-0.502803

(8664, 5374)

(8664, 5370)

(8664, 4722)

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

(9806, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.239901,-3.120830,-3.069606,6.872059,-0.438361,-2.307343,-9.542530,0.802866,8.061898,3.624429,...,0.328696,0.104488,-0.157027,0.102525,0.041685,-0.374804,0.563802,-0.330302,0.202280,-0.414151
1,-1.522250,2.160470,-0.764794,-2.747562,3.436039,-1.738368,-8.491585,-1.121171,2.967846,-0.322529,...,-0.427419,0.082512,-0.980037,-0.345990,0.260759,0.039344,0.626098,-0.006609,0.099882,-0.441397
2,0.779026,-1.142178,-3.798127,4.844985,0.165893,-0.363051,-10.758794,-1.032117,7.527507,3.507289,...,0.506235,-0.206587,-0.396478,-0.397290,0.062021,-0.324190,0.746121,0.234986,0.488707,-0.656754
3,-3.102104,-3.598334,-3.687218,4.628766,8.471542,3.261075,-24.245876,-5.795103,14.844986,-6.802896,...,0.620533,-0.348755,-0.745056,-0.326395,-0.117034,-0.271841,0.448255,0.269917,0.509724,-0.743291
4,2.633740,0.598996,-2.097617,4.945745,0.922130,-0.963978,-3.949562,-0.782235,3.508466,6.184474,...,0.121952,-0.330718,-0.631405,0.090258,0.344520,0.285170,1.165105,-0.720850,0.216233,0.139632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9801,2.996846,-6.876090,-4.976286,11.258199,-1.000952,-3.922870,-15.009562,1.349784,9.886626,4.320618,...,-0.147974,0.055805,-0.247672,-0.042824,0.089978,-0.584960,0.997437,-0.030343,0.172525,-0.835031
9802,1.313483,-5.218432,-1.885624,8.857142,-1.579081,-2.085158,-12.803849,2.294089,8.360367,3.834403,...,-0.124902,0.106578,-0.374287,0.331871,0.030688,-0.654470,0.731841,0.116658,0.081830,-0.890827
9803,1.876266,-3.608840,-0.707561,6.947767,-1.400545,-2.774024,-10.946277,0.854028,6.144766,3.147989,...,-0.120525,0.209860,-0.292190,0.055057,0.107484,-0.609680,0.535056,-0.159786,0.270970,-0.620100
9804,2.906470,-2.345170,-4.124988,8.035068,0.534096,-1.144006,-13.293423,-1.884828,3.590167,4.703815,...,-0.510301,0.346223,-0.445023,0.033796,0.129996,-0.488082,0.787072,0.071922,0.026902,-0.618977
9805,1.500076,-4.428866,-0.767467,5.931848,-1.000949,-1.674771,-10.132780,1.911930,5.460685,3.017065,...,-0.269924,0.235000,-0.397132,0.249892,0.253434,-0.586575,0.759668,0.075181,-0.030277,-0.743027

(9806, 5374)

(9806, 5370)

(9806, 4722)

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/pandas/core/dtypes/astype.py:133: RuntimeWarning: overflow encountered in cast
  return arr.astype(dtype, copy=True)

(22060, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [6]:
X1_all.X.to_csv("HIV/mod_data/X1.1")
X2_all.X.to_csv("HIV/mod_data/X2.1")
X3_all.X.to_csv("HIV/mod_data/X3.1")
X1_all.y.to_csv("HIV/mod_data/y1.1")
X2_all.y.to_csv("HIV/mod_data/y2.1")
X3_all.y.to_csv("HIV/mod_data/y3.1")

In [109]:
import pandas as pd
import numpy as np

# Předpokládám, že load_datasets vrací objekt s atributy getDF(), X a y
# a že getDF() vrací pandas DataFrame.

# Načtení dat pro první iteraci (mimo cyklus)
X1_all = load_datasets("HIV/data/hiv_train_1")
X2_all = load_datasets("HIV/data/hiv_val_1")
X3_all = load_datasets("HIV/data/hiv_test_1")

smiles1 = pd.concat([X1_all.getDF()["Drug"], X2_all.getDF()["Drug"], X3_all.getDF()["Drug"]]).reset_index(drop=True)
X_all = pd.concat([X1_all.X, X2_all.X, X3_all.X])
y_all = pd.concat([X1_all.y, X2_all.y, X3_all.y])

for i in range(2, 11):
    X1_all2 = load_datasets(f"HIV/data/hiv_train_{i}")
    X2_all2 = load_datasets(f"HIV/data/hiv_val_{i}")
    X3_all2 = load_datasets(f"HIV/data/hiv_test_{i}")

    smiles2 = pd.concat([X1_all2.getDF()["Drug"], X2_all2.getDF()["Drug"], X3_all2.getDF()["Drug"]]).reset_index(drop=True)
    display(smiles2)
    
    # Změna: Ignorujeme léky, které nejsou v smiles1 a mažeme je z datasetů
    valid_smiles = smiles2[smiles2.isin(smiles1)] # Filtrujeme smiles2 na platné
    indices_map = [list(smiles1).index(element) for element in valid_smiles] # Používáme filtrované smiles2
    
    # Upravíme původní DataFrames X1_all2, X2_all2, X3_all2
    X1_all2.df[X1_all2.getDF()["Drug"].isin(smiles1)]
    X2_all2.df[X2_all2.getDF()["Drug"].isin(smiles1)]
    X3_all2.df[X3_all2.getDF()["Drug"].isin(smiles1)]

    # Opatrně s indexováním y_all, pokud indices_map může být kratší!
    #if indices_map:
     ###   y_all_selected = y_all.iloc[indices_map]
    #else:
     #   y_all_selected = pd.Series([])
    indices_map = [list(smiles1).index(element) for element in pd.concat([X1_all2.df["Drug"],X2_all2.df["Drug"],X3_all2.df["Drug"]])]
    y_concat = pd.concat([X1_all2.df.Y, X2_all2.df.Y, X3_all2.df.Y])
    y_all_selected = y_all.iloc[indices_map]
    if np.array_equal(y_all_selected.values, y_concat.values):
        print("good")
    else:
        print("Critical error")
        break

    # Opatrně s indexováním X_all, pokud indices_map může být kratší!
    X_res = X_all.iloc[indices_map]

    
    X1_res = X_res.iloc[:X1_all2.getDF().shape[0]] 
    X2_res = X_res.iloc[X1_all2.getDF().shape[0]:-X3_all2.getDF().shape[0]] 
    X3_res = X_res.iloc[-X3_all2.getDF().shape[0]:]

    X1_res.to_csv(f"HIV/mod_data/X1.{i}")
    X2_res.to_csv(f"HIV/mod_data/X2.{i}")
    X3_res.to_csv(f"HIV/mod_data/X3.{i}")
    X1_all2.y.to_csv(f"HIV/mod_data/y1.{i}")
    X2_all2.y.to_csv(f"HIV/mod_data/y2.{i}")
    X3_all2.y.to_csv(f"HIV/mod_data/y3.{i}")

0        CCC1=[O+][Cu-3]2([O+]=C(CC)C1)[O+]=C(CC)CC(CC)...
1        C(=Cc1ccccc1)C1=[O+][Cu-3]2([O+]=C(C=Cc3ccccc3...
2          Nc1ccc(C=Cc2ccc(N)cc2S(=O)(=O)O)c(S(=O)(=O)O)c1
3                                   O=S(=O)(O)CCS(=O)(=O)O
4                               CCOP(=O)(Nc1cccc(Cl)c1)OCC
                               ...
40665    COc1ccc(C=C2CN(C)CC3C2=NN(c2ccccc2)C3c2ccc(OC)...
40666        CN1CC(=Cc2cccs2)C2=NN(c3ccccc3)C(c3cccs3)C2C1
40667             CN1CC(=Cc2cccs2)C2=NC(=S)NC(c3cccs3)C2C1
40668      CN1CC(=Cc2cccs2)C2=C(C1)C(c1cccs1)C(C#N)=C(N)O2
40669               CN1CC(=Cc2cccs2)C2=NN(C)C(c3cccs3)C2C1
Name: Drug, Length: 40670, dtype: object

Critical error

In [111]:
    X1_all2 = load_datasets(f"HIV/data/hiv_train_{2}")
    X2_all2 = load_datasets(f"HIV/data/hiv_val_{2}")
    X3_all2 = load_datasets(f"HIV/data/hiv_test_{2}")

In [112]:
    smiles2 = pd.concat([X1_all2.getDF()["Drug"], X2_all2.getDF()["Drug"], X3_all2.getDF()["Drug"]]).reset_index(drop=True)
    display(smiles2.shape)

(40670,)

In [ ]:
    # Změna: Ignorujeme léky, které nejsou v smiles1 a mažeme je z datasetů
    valid_smiles = smiles2[smiles2.isin(smiles1)] # Filtrujeme smiles2 na platné
    indices_map = [list(smiles1).index(element) for element in valid_smiles] # Používáme filtrované smiles2

In [118]:
    #display(valid_smiles.shape)
    display(len(indices_map))

40670

In [120]:
smiles2.isin(smiles1).sum()

40670

In [ ]:
    # Upravíme původní DataFrames X1_all2, X2_all2, X3_all2
    X1_all2.df[X1_all2.getDF()["Drug"].isin(smiles1)]
    X2_all2.df[X2_all2.getDF()["Drug"].isin(smiles1)]
    X3_all2.df[X3_all2.getDF()["Drug"].isin(smiles1)]

In [ ]:
    indices_map = [list(smiles1).index(element) for element in pd.concat([X1_all2.df["Drug"],X2_all2.df["Drug"],X3_all2.df["Drug"]])]
    y_concat = pd.concat([X1_all2.df.Y, X2_all2.df.Y, X3_all2.df.Y])
    y_all_selected = y_all.iloc[indices_map]
    if np.array_equal(y_all_selected.values, y_concat.values):
        print("good")
    else:
        print("Critical error")
        break

    # Opatrně s indexováním X_all, pokud indices_map může být kratší!
    X_res = X_all.iloc[indices_map]

    
    X1_res = X_res.iloc[:X1_all2.getDF().shape[0]] 
    X2_res = X_res.iloc[X1_all2.getDF().shape[0]:-X3_all2.getDF().shape[0]] 
    X3_res = X_res.iloc[-X3_all2.getDF().shape[0]:]

    X1_res.to_csv(f"HIV/mod_data/X1.{i}")
    X2_res.to_csv(f"HIV/mod_data/X2.{i}")
    X3_res.to_csv(f"HIV/mod_data/X3.{i}")
    X1_all2.y.to_csv(f"HIV/mod_data/y1.{i}")
    X2_all2.y.to_csv(f"HIV/mod_data/y2.{i}")
    X3_all2.y.to_csv(f"HIV/mod_data/y3.{i}")

KeyboardInterrupt:

In [51]:
smiles1["Drug"].nunique()

40564

In [50]:
df["Drug"].nunique()

40565

In [54]:
len(set_smiles)

40564

In [99]:
ind = 0
X3_all = load_datasets("HIV/data/hiv_test_1")
set_smiles = set(smiles1["Drug"])
for index, element in df_add.getDF().iterrows():
    if element["Drug"] not in set_smiles:
        print(ind, element["Drug"])
        X3_all.df.loc[ind] = element
        ind += 1

0 CS(C)=O
1 O=S(c1ccccc1O)S(=O)c1ccccc1O
2 O=S1c2ccccc2Sc2ccccc21
3 O=S1c2ccccc2S(=O)c2ccccc21
4 O=S(c1ccc(Cl)cc1)S(=O)c1ccc(Cl)cc1
5 Cc1ccc2c(c1)S(=O)c1cc(C)ccc1S2
6 CC1S(=O)C(C)S(=O)C(C)S1=O
7 O=S1CCCCS1
8 CSCS(=O)CC(CO)NC(=O)C=Cc1c(C)nc(O)nc1O
9 Cc1c2ccccc2n[c-](CS(=O)c2ccccc2)[n+]1=O
10 Cc1c2ccccc2n[c-](CS(C)=O)[n+]1=O
11 CN(C)C1C(O)=C(C(=O)NCNC(CCS(C)=O)C(=O)O)C(=O)C2(O)C(O)=C3C(=O)c4c(O)cccc4C(C)(O)C3CC12
12 Cc1c(S(=O)c2cc(C(C)(C)C)c(O)c(CN3CCCC3)c2C)cc(C(C)(C)C)c(O)c1CN1CCCC1
13 CC(C)(C)SS(=O)C(C)(C)C
14 O=C1CC2CCCC(C1)S2=O
15 O=S(CC(O)c1ccccc1)c1ccccc1
16 O=S1CC(c2ccccc2)=C(c2ccccc2)CS1
17 CN1CCCCC1CCN1c2ccccc2Sc2ccc(S(C)=O)cc21
18 Cc1ccc(CS(=O)C(Cl)(Cl)c2ccc(C)cc2)cc1
19 O=S(CC=CCS(=O)c1ccccc1)c1ccccc1
20 Cc1nc(O)nc(O)c1C=CC(=O)NC(CO)CS(=O)Cc1ccccc1
21 Cn1c(=O)c(S(C)=O)c(O)c2ccccc21
22 CC(=O)OC1CSS(=O)CC1OC(C)=O
23 O=S(Cc1ccc2c(c1)OCO2)c1ccccc1
24 O=C1OC2CS(=O)CC2O1
25 Cn1c2c(c(=O)n(C)c1=O)CS(=O)c1ccccc1N2
26 CS(=O)(=O)CS(=O)CS(=O)CS(=O)CC(NC(=O)CCC(N)C(=O)O)C(=O)O
27 O=C(c1ccccc1)C1C(c2ccccc2)S(=O)C(c2ccccc2)CC1(O)c1ccccc1
28 CS(=O)CC(=O)c1ccccn1
29 O=S(Cl)C(Cl)=C(Cl)Cl
30 CS(=O)CCN=Cc1ccc(N=Nc2ccc(O)cc2)cc1
31 Cc1c(COC(=O)NC(C)C)c(COC(=O)NC(C)C)c2n1CS(=O)C2
32 CCNC(=O)c1ccccc1S(C)=O
33 O=[N+]([O-])c1ccccc1S(=O)NCc1c(Cl)cccc1Cl
34 CC1CC(C)S(=O)C(C)S1
35 CN=S(=O)(c1ccccc1)C1(C)CC(C)=C(C)CS1=O
36 CSC(=Cc1ccc(C(=O)c2ccc(C)cc2)n1C)S(C)=O
37 O=[N+]([O-])c1ccccc1S(=O)c1ccccc1[N+](=O)[O-]
38 CC1=C(C)CS(=O)N(c2ccccc2)C1
39 CCCCS(=O)CCC(N)C(=O)O
40 O=NNc1ccc(S(=O)c2ccccc2)cn1
41 COc1ccc(S(=O)(=O)O)cc1-n1nc(C(=O)Nc2ccccc2)n[n+]1-c1cc(S(=O)(O)=[OH+])ccc1OC
42 Cc1cccc(N2C(c3ccccc3)c3ccc(C)cc3NS2=O)c1
43 CC(C)NC(=O)OCCS(=O)c1c(Cl)c(Cl)nn1C
44 CC(=O)[OH+][Zn-2]12[N+](=Cc3cccc[n+]31)Nc1ccc3ccccc3[n+]12
45 CC(=O)[OH+][Zn-2]12[OH+]c3c(C)ncc(CO)c3C=[N+]1NC(N)=[S+]2
46 C=CCSSC=CCS(=O)CC=C
47 CSC1=[S+][Zn-2]2([OH+]C(C)=O)[OH+]c3c(C)ncc(CO)c3C=[N+]2N1
48 C[N+](C)(C)CCOP(=O)(O)OP(O)(=[OH+])OCC1CCC(n2ccc(=N)[nH]c2=O)O1
49 O=S1CSCS1
50 O=C(CC1C(=O)Nc2ccccc2S1=O)Nc1ccc(Cl)cc1
51 Cc1cccc(C(C)(C)C)c1NC(=O)CC1C(=O)Nc2ccccc2S1=O
52 CCc1cccc(C)c1NC(=O)CC1C(=O)Nc2ccccc2S1=O
53 Cc1ccc(S(=O)(=O)OC2CSS(=O)CC2OS(=O)(=O)c2ccc(C)cc2)cc1
54 O=S1Cc2ccccc2CSS1
55 O=S1Cc2ccccc2CS1
56 C=C=C(C(=O)OC)S(=O)c1ccccc1[N+](=O)[O-]
57 C=C=C(C(=O)OC)S(=O)c1ccc([N+](=O)[O-])cc1[N+](=O)[O-]
58 COC(=O)C1=C(CS(=O)c2ccccc2[N+](=O)[O-])C2C=CC1C2
59 COC(=O)C1=C(CS(=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])C2C=CC1C2
60 COC(=O)C1=C(CS(=O)c2ccccc2[N+](=O)[O-])ON(C)C1c1ccccc1
61 COC(=O)C1=C(CS(=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])ON(C)C1c1ccccc1
62 COC(=O)c1c(C(=O)OC)c(C(=O)OC)[c-](C(=O)OC)c1C(=O)OC
63 CSc1nnc([C-](C#N)C#N)nn1
64 CC(=O)[OH+][Zn-2]12[N+](=C(c3ccccc3)c3cccc[n+]31)Nc1cccc[n+]12
65 CSc1c(S(C)=O)[nH]c2cc(Br)cc(Br)c12
66 CC(=O)[OH+][Zn-2]12[OH+]c3c(Cl)cc(Cl)cc3C=[N+]1Nc1cccc[n+]12
67 CC(=O)[OH+][Zn-3]12([OH+]C(C)=O)Oc3c(Cl)cc(Cl)cc3C=[N+]1NC(c1ccncc1)=[O+]2
68 Oc1ccc(C2Oc3cc(O)cc4c3C(=[O+][AlH3-3]35([O+]=C6c7c(cc(O)cc7[OH+]3)OC(c3ccc(O)cc3O)C6O)([O+]=C3c6c(cc(O)cc6[OH+]5)OC(c5ccc(O)cc5O)C3O)[OH+]4)C2O)c(O)c1
69 O=C1[OH+][Zn-4]234([O+]=C(c5cccs5)C=[N+]2c2ccccc21)[O+]=C(c1cccs1)C=[N+]3c1ccccc1C(=O)[OH+]4
70 C1=[N+]2c3ccccc3[SH+][Zn-4]234([O+]=C1c1ccco1)[O+]=C(c1ccco1)C=[N+]3c1ccccc1[SH+]4
71 O=C1c2ccccc2C(=O)c2cc3c(cc21)CS(=O)C3
72 O=S1C(c2ccccc2)c2c(-c3ccccc3)sc(-c3ccccc3)c2C1c1ccccc1
73 O=S1Nc2c(Cl)cc(Cl)c3c(Cl)cc(Cl)c(c23)N1
74 COC(=O)c1sc(C(=O)OC)c2c1CS(=O)C2
75 N#CC1(C2SCCS2=O)C2=C(C(=O)c3ccccc3C2=O)N2CCCC21
76 O=S1C(=c2ccc(=C3Sc4ccccc4S3)cc2)Sc2ccccc21
77 C=CCC1(C)CCCCC1(O)CS(=O)c1ccccc1
78 O=[N+]([O-])c1ccccc1S(=O)c1ccccc1
79 Cc1ccc(S(=O)c2ccccc2[N+](=O)[O-])cc1
80 O=S(c1ccccc1)c1ccccc1
81 CC(C)CCCC(C)C1CCC2C3CC=C4CC(C(=O)NCC[N+](C)(C)CCCS(=O)(O)=[OH+])CCC4(C)C3CCC12C
82 O=[N+]([O-])c1ccc(C2=Nc3ccccc3S(=O)C(c3ccccc3)C2)cc1
83 O=S1c2ccccc2N=C(c2ccc3ccccc3c2)CC1c1ccccc1F
84 CC(=O)Nc1ccc(C2CC(c3ccc([N+](=O)[O-])cc3)=Nc3ccccc3S2=O)cc1
85 O=[N+]([O-])c1ccc(C2CC(c3ccccc3Cl)=Nc3ccccc3S2=O)cc1
86 O=S1c2ccccc2N=C(c2ccc3ccccc3c2)CC1C1=CC=CCC1
87 O=S1c2ccccc2NC(c2ccc3ccccc3c2)CC1c1ccccc1
88 O=S1c2ccccc2N=C(c2cccs2)CC1c1ccccc1O
89 CC1=C(C)CC2(CCCCC2=O)S(=O)C1
90 O=C(CC1C(=O)Nc2ccccc2S1=O)Nc1cccc(Cl)c1
91 Nc1ccccc1S(=O)c1ccccc1
92 CC(=O)Nc1ccccc1S(=O)c1ccccc1
93 O=S1c2ccccc2-c2ccccc21
94 O=S1(=O)[OH+][Zn-4]23([O+]=C4NC=Nc5[nH][n+]2cc54)([O+]=C2NC=Nc4[nH][n+]3cc42)[OH+]1
95 O=S1C=C(C2=COCCC2)OC1
96 CC1=C2OCS(=O)C2C2C(=O)N(c3ccccc3)C(=O)C2C1
97 O=C1C2CC=C3CCS(=O)C3C2C(=O)N1c1ccccc1
98 O=C(CC1C(=O)Nc2ccccc2S1=O)Nc1ccccc1
99 CCOc1ccc(NC(=O)CC2C(=O)Nc3ccccc3S2=O)cc1
100 Cc1ccc(NC(=O)CC2C(=O)Nc3ccccc3S2=O)c(C)c1
101 Cc1ccc(NC(=O)CC2C(=O)Nc3ccccc3S2=O)cc1C
102 O=C(CC1C(=O)Nc2ccccc2S1=O)Nc1cc(Cl)ccc1Cl
103 CCOc1ccccc1NC(=O)CC1C(=O)Nc2ccccc2S1=O
104 Cc1ccccc1NC(=O)CC1C(=O)Nc2ccccc2S1=O
105 CCc1cccc(C(C)CC)c1NC(=O)CC1C(=O)Nc2ccccc2S1=O
106 O=S1c2ccccc2N=C(c2cccc3ccccc23)CC1c1cccc2ccccc12
107 O=C(O)c1ccc(CS(=O)c2ccccc2)c([N+](=O)[O-])c1
108 Cc1ccc(S(=O)Cc2ccc(C(=O)O)cc2[N+](=O)[O-])cc1
109 COc1ccc(S(=O)Cc2ccc(C(=O)O)cc2[N+](=O)[O-])cc1
110 O=C(O)c1ccc(CS(=O)c2ccc([N+](=O)[O-])cc2)c([N+](=O)[O-])c1
111 Nc1ccc(S(=O)Cc2ccc(C(=O)O)cc2[N+](=O)[O-])cc1
112 O=C(O)c1ccc(CS(=O)c2ccccc2C(=O)O)c([N+](=O)[O-])c1
113 CCOC(=O)c1ccc(CS(=O)c2ccccc2)c([N+](=O)[O-])c1
114 CCOC(=O)c1ccc(CS(=O)c2ccc(OC)cc2)c([N+](=O)[O-])c1
115 CCOC(=O)c1ccc(CS(=O)c2ccc([N+](=O)[O-])cc2)c([N+](=O)[O-])c1
116 CCOC(=O)c1ccc(CS(=O)c2ccc(N)cc2)c([N+](=O)[O-])c1
117 CC(C)CCCC(C)C1CCC2C3CC=C4CC(OP(O)(=[OH+])OCC[N+](C)(C)C)CCC4(C)C3CCC12C
118 O=S1c2ccccc2N=C(c2ccc(Cl)cc2)CC1c1cccs1
119 O=C1[OH+][Zn-4]234([O+]=C(c5ccco5)C=[N+]2c2ccccc21)[O+]=C(c1ccco1)C=[N+]3c1ccccc1C(=O)[OH+]4
120 O=S1Nc2cccc(C(F)(F)F)c2S1
121 O=S1Nc2c(Cl)cc(Cl)c(Cl)c2S1
122 Cc1cc(C)c2c(c1)NS(=O)S2
123 CCOC(=O)c1ccc(CS(=O)c2ccc(C)cc2)c([N+](=O)[O-])c1
124 COc1cccc2c1[OH+][Zn-2]1(O)[O+]=C(N)N[N+]1=C2
125 COc1cccc2c1[OH+][Zn-2]1([O+]=C2)[O+]=Cc2cccc(OC)c2[OH+]1
126 COc1cccc2c1[OH+][Zn-2]1(O)[S+]=C(N)N[N+]1=C2
127 COc1cccc2c1[OH+][Zn-2]1(O)[S+]=C(Nc3ccccc3)N[N+]1=C2
128 COc1cccc2c1[OH+][Zn-2]1(O)[O+]=C(c3ccncc3)N[N+]1=C2
129 CC1=C2[OH+][AlH3-3]34([O+]=C2C=CN1C)([O+]=C1C=CN(C)C(C)=C1[OH+]3)[O+]=C1C=CN(C)C(C)=C1[OH+]4
130 CCCCCCCCCCCCCCCCCCOP(O)(=[OH+])OC1CC[N+](C)(C)CC1
131 O=c1ccn(C2CC(CO)CS(=O)C2)c(=O)[nH]1
132 O=S1c2ccccc2N=C(c2ccc3ccccc3c2)CC1c1ccccc1
133 CC1CC(c2ccc([N+](=O)[O-])cc2)=Nc2ccccc2S1=O
134 CCCCN(CC)C(=O)C(=O)C1C(=O)Nc2ccccc2S1=O
135 O=S(c1ccccc1)C1CC2C3CC4C2C4C31
136 O=C1CS(=O)c2ccccc2N1
137 CC(C)(C)NN=C(C(=O)Nc1nc(=S)[nH][nH]1)C1C(=O)Nc2ccccc2S1=O
138 NNC(=S)NN=C(C(=O)Nc1cc(Cl)ccc1Cl)C1C(=O)Nc2ccccc2S1=O
139 COC(=O)C1C2C=CC(C2)C1(C(=O)OC)S(=O)CC12CCC(CC1O)C2(C)C
140 O=S1Cc2nc3ccccc3n2C1c1c(F)cccc1F
141 CC(=O)n1c2c(c(=O)n1-c1ccccc1)S(=O)CCC2
142 CC1=CC(O)C(=O)C=CC=Cc2csc(n2)C(C)NC(=O)CC2(CC1)S(=O)SC(=O)C2(C)O
143 CCOc1ccccc1NC(=O)C(=O)C1C(=O)Nc2ccccc2S1=O
144 CC(C)(C)NN=C(C(=O)Nc1cccc(Cl)c1)C1C(=O)Nc2ccccc2S1=O
145 O=C(Nc1nc(=S)[nH][nH]1)C(=O)C1C(=O)Nc2ccccc2S1=O
146 COc1ccccc1NC(=O)C(=O)C1C(=O)Nc2ccccc2S1=O
147 O=S(Cc1cc2c(cc1Br)OCO2)c1ccccc1
148 O=S1c2ccc(Cl)cc2CC(SSC2Cc3cc(Cl)ccc3S(=O)c3ccccc32)c2ccccc21
149 CCc1cccc(C(C)C)c1NC(=O)C(=O)C1C(=O)Nc2ccccc2S1=O
150 CCOc1ccc(NC(=O)C(=O)C2C(=O)Nc3ccccc3S2=O)cc1
151 CC(=O)c1cccc(NC(=O)C(=NNC(=S)NN)C2C(=O)Nc3ccccc3S2=O)c1
152 CCOc1ccccc1NC(=O)C(=NNC(C)(C)C)C1C(=O)Nc2ccccc2S1=O
153 CCOc1ccc(NC(=O)C(=NNC(C)(C)C)C2C(=O)Nc3ccccc3S2=O)cc1
154 CC(C)(C)C(=CS(=O)N=Cc1ccccc1)C(C)(C)C
155 CC1(C)COC(c2c(-c3ccccc3)noc2CS(=O)c2ccccc2)=N1
156 O=S1CCS(=O)CCS(=O)CC1
157 CC(=O)OCC1=C(CCC#N)N2C(=O)C(NC(=O)Cc3cccs3)C2S(=O)C1
158 O=S(Cc1ccccc1)c1nc2ccccc2nc1-c1cccs1
159 O=S(Cc1cnc2ccccc2c1)c1nc2ccccc2nc1-c1cccs1
160 O=S(Cc1ccccn1)c1nc2ccccc2nc1-c1ccccc1
161 CC(=O)Nc1ccc(S(=O)c2ccc(NC(C)=O)cc2)cc1
162 COc1ccc(S(=O)c2ccc(OC)cc2)cc1
163 CN(C)c1ccc(S(=O)c2ccc(N(C)C)cc2)cc1
164 Cc1ccc(S(=O)c2cccs2)cc1
165 Cc1cc(C)c(NS(=O)c2cccc(Cl)c2)c(C)c1
166 Cc1cc(C)c(NS(=O)c2cccc(C(F)(F)F)c2)c(C)c1
167 Cc1cc(C)c(NS(=O)c2cccc([N+](=O)[O-])c2)c(C)c1
168 Cc1cc(C)c(NS(=O)c2ccc(Cl)cc2)c(C)c1
169 CCCCCCCCCCCCCCCCOCC(COP(O)(=[OH+])OCC[n+]1ccc(N(C)C)cc1)OCC
170 O=S(Cc1ccccc1)c1ccccc1Cn1cccc1
171 O=[N+]([O-])c1ccc2[nH]c(=S)n(C=C(c3ccccc3)S(=O)Cc3ccccc3)c2c1
172 CC(=O)Nc1ccc(C=C2SC(=S)N(C=C(c3ccccc3)S(=O)Cc3ccccc3)C2=O)cc1
173 O=S(Cc1ccccc1)C(=CNC(=S)Nc1cc(Cl)ccc1Cl)c1ccccc1
174 O=C1CN(C=C(c2ccccc2)S(=O)Cc2ccccc2)C(=S)N1
175 Cc1ccc2c(c1)[nH]c(=S)n2C=C(c1ccccc1)S(=O)Cc1ccccc1
176 CCc1cccc(C(C)(C)C)c1NC(=S)NC=C(c1ccccc1)S(=O)Cc1ccccc1
177 O=C1Nc2ccccc2C1=NNC(=S)NC=C(c1ccccc1)S(=O)Cc1ccccc1
178 CC(C)=CCS(=O)c1ccccc1NC1=CC(=O)CC(C)(C)C1
179 C=CCNC(=S)NC=C(c1ccccc1)S(=O)Cc1ccccc1
180 O=S(Cc1ccccc1)C(=CNC(=S)Nc1ccccc1)c1ccccc1
181 Cc1ccc(NC(=S)NC=C(c2ccccc2)S(=O)Cc2ccccc2)c(C)c1
182 O=S(Cc1ccccc1)C(=Cn1c(=S)[nH]c2ccccc21)c1ccccc1
183 O=C(NC=C(c1ccccc1)S(=O)Cc1ccccc1)Nc1ccccc1Cl
184 O=c1ccn(C=C(c2ccccc2)S(=O)Cc2ccccc2)c(=S)[nH]1
185 Cc1cn(C2CC(S(=O)c3ccccc3)C(CO)O2)c(=O)[nH]c1=O
186 O=S(C=CC=CS(=O)(=O)c1ccccc1)c1ccccc1
187 C[Si](C)(C)C#CC(O)CS(=O)c1ccccc1
188 O[Zn-2]12[O+]=C(N[N+]1=Cc1ccccc1)c1ccccc1[OH+]2
189 CSc1c(S(C)=O)c2ccccc2n1C
190 C=C1CCCCCCCCCCC1S(=O)c1ccccc1
191 O=S(CC1(O)CCCCC1)c1ccccc1
192 COC(=O)CC(C)(NS(=O)c1ccc(C)cc1)c1ccccc1
193 O=C1CC(c2ccccc2)S(=O)c2ccccc2N1
194 CCCCS(=O)CCC(N)P(=O)(O)O
195 O=C1CC2CCC(C1)S2=O
196 CC(=O)OC1C=CC(OC(C)=O)C2C1C1C3C=CC=CC3C2S1=O
197 Cc1ccc(S(=O)CC(CF)OCn2cc(C)c(=O)[nH]c2=O)cc1
198 COc1ccc(S(=O)Cc2cc(OC)ccc2OC)cc1
199 COc1cc(CS(=O)c2ccc(O)cc2)cc(OC)c1OC
200 CNc1ccc(S(=O)Nc2ccc(OC)cc2)cc1
201 O=S(Nc1ccccc1)c1ccc(Cl)cc1
202 COc1ccc(NS(=O)c2ccc(OC)cc2)cc1
203 CNc1ccc(S(=O)Nc2ccccc2)cc1
204 O=S(Nc1ccccc1)c1ccc(-c2ccccc2)cc1
205 COc1ccc(NS(=O)c2c(C)cc(C)cc2C)cc1
206 O=S(Nc1ccccc1)c1ccc(N2CCOCC2)cc1
207 COc1ccc(NS(=O)CCCc2ccccc2)cc1
208 COc1ccccc1S(=O)Nc1ccccc1
209 O=S(Nc1ccccc1)c1ccc(Cl)c(Cl)c1
210 COc1ccc(NS(=O)c2ccc(Cl)cc2)cc1
211 CN(C)c1ccc(S(=O)Nc2ccccc2)cc1
212 COc1ccc(NS(=O)c2ccccc2OC)cc1
213 O=S(CCc1ccccc1)Nc1ccccc1
214 COc1ccc(NS(=O)C2CCCCC2)cc1
215 COc1ccc(NS(=O)CCc2ccccc2)cc1
216 COc1ccc(NS(=O)c2cccc(C)c2)cc1
217 COc1ccc(NS(=O)c2ccc(-c3ccccc3)cc2)cc1
218 O=S(Nc1ccccc1)c1cccc(Cl)c1
219 O=S(Nc1ccccc1)c1ccccc1Oc1ccccc1
220 Cc1ccc(S(=O)S(=O)c2ccc(C)cc2)cc1
221 CC(C)C1C(=O)N(c2c(F)c(F)c(F)c(F)c2F)C(=S)N1CCS(=O)c1ccccc1
222 Cc1c(C)n(-c2ccccc2)c2nc(S(C)=O)nc(S(C)=O)c12
223 OC(=[OH+])C1([n+]2c(-c3ccccc3)cc(-c3ccccc3)cc2-c2ccccc2)CC1
224 Cc1ccc(S(=O)c2occc2C=O)cc1
225 CCOC1CCC(S(=O)c2ccc(C)cc2)=CO1
226 CC1=C(S(=O)c2ccc(C)cc2)CCC2(CCCCO2)O1
227 [N-]=NCC(=O)OC(COCc1ccccc1)COCc1ccccc1
228 COc1ccc(S(=O)(=O)n2c3c(c4ccccc42)C2C(CCCN2C(=O)CS(=O)c2ccc(C)cc2)C(Cl)C3)cc1
229 C[N+](C)(C)C(CSSCC(C(O)=[OH+])[N+](C)(C)C)C(=O)O
230 C[N+]1(C)CC[N+](C)(C)B1[C-](O)O
231 COC(=O)C1=C(C)NC2=C(C(=O)CCC2)C1CCS(C)=O
232 Cc1ccc(S(=O)c2sccc2C=O)cc1
233 CCCCCCCCCCCCCC=CC1C(C(=O)OC)N1S(=O)c1ccc(C)cc1
234 O=S(c1ccc(Cl)cc1)c1ccccc1C1=NCCN1
235 C1C[N+]23CCC[N+]4(C1)CC[S-]1[Fe+2]24([SH+]CC3)[S-]2CC[N+]34CCC[N+]5(CCC3)CC[SH+][Fe+2]1254
236 CCSC(C(COC(C)=O)OC(C)=O)S(=O)CC
237 CS(=O)CC1=NOC(c2ccccc2)C1c1ccccc1
238 Cc1ccc(S(=O)CC2=NOC(c3ccccc3)C2c2ccccc2)cc1
239 CS(=O)C(C1=NOC(c2ccccc2)C1c1ccccc1)C(O)C1COC(C)(C)O1
240 c1ccc2c(c1)[SH+][GeH2+]([SH+]c1ccccc1[SH+][GeH2+]1[SH+]c3ccccc3[SH+]1)[SH+]2
241 O=C1SS(=O)c2ccccc21
242 CN(C)c1cc(CN(CCSS(=O)c2ccccc2[N+](=O)[O-])S(=O)c2ccccc2[N+](=O)[O-])nc(CN(CCSS(=O)c2ccccc2[N+](=O)[O-])S(=O)c2ccccc2[N+](=O)[O-])c1
243 C#CCCOC(=O)CC1=C(C)C(=Cc2ccc(S(C)=O)cc2)c2ccc(F)cc21
244 O=C1c2cccnc2S(=O)N1Cc1ccccc1
245 CCOC(=O)NN=CC1=NN(C(=O)OCC)S(=O)C1C
246 CCOC(=O)N1N=C(C(C)=NOC)C(C)S1=O
247 COc1ccc(NC(CS(=O)c2ccc(C)cc2)C(F)(F)F)cc1
248 COc1ccc(NC(C(c2ccccc2)S(=O)c2ccc(C)cc2)C(F)(F)F)cc1
249 Cc1ccc(S(=O)C=C(NC(=O)OCc2ccccc2)C(F)(F)F)cc1
250 COc1ccc(N=C(CS(=O)c2ccc(C)cc2)C(F)(F)F)cc1
251 O=S1c2ccccc2SCSc2ccccc21
252 COC(=O)C(NC(=O)OCc1ccccc1)(C(C)S(=O)c1ccc(C)cc1)C(F)(F)F
253 Cc1ccc(S(=O)CC(NC(=O)OCc2ccccc2)(Sc2ccccc2)C(F)F)cc1
254 Cc1ccc(S(=O)CC2(C(F)F)NC(=O)NC2=O)cc1
255 COC(=O)C1=C(C(=O)OC)C2OC1C1C2C2(C)C(C)=C(C)C1(C)S2=O
256 CC12C=CC(C)(C3C(=O)C4C(C(=O)C31)C1(C)C=CC4(C)S1=O)S2=O
257 CC(C)(C)[Si](C)(C)OCC1OC(n2ccc(=O)[nH]c2=O)C(O[Si](C)(C)C(C)(C)C)C12NC(C(N)=O)CS2=O
258 O=C1CCC2(CC1CCS(=O)c1ccccc1)OCCO2
259 O=S(c1ccccc1)C1CC2CC3(CCC21O)OCCO3
260 CCOC(=O)C1(C(C)=O)CC(C)=C(C)CS1=O
261 CCS(=O)c1c2cc(OC)ccc2nc2ccc(OC)cc12
262 O=S(CCCl)c1c2ccccc2nc2ccccc12
263 COc1ccc2nc3ccc(OC)cc3c(S(=O)CCCl)c2c1
264 CCN(CC)CCS(=O)c1c2cc(OC)ccc2nc2ccc(OC)cc12
265 COc1ccc2nc3ccc(OC)cc3c(S(=O)Cc3ccccc3)c2c1
266 COc1ccc2nc3ccc(OC)cc3c(S(=O)Cc3ccc([N+](=O)[O-])cc3)c2c1
267 O=C1Sc2ccccc2C(=O)N2CS(=O)CC12
268 Cc1cn(COCCS(=O)c2ccccc2)c(=O)[nH]c1=O
269 Cc1cn(COCCCS(=O)c2ccccc2)c(=O)[nH]c1=O

In [97]:
X3_all = cls.transform(X3_all)

KeyError: "None of [Index(['A2ARDataset_00000', 'A2ARDataset_00001', 'A2ARDataset_00002',\n       'A2ARDataset_00003', 'A2ARDataset_00004', 'A2ARDataset_00005',\n       'A2ARDataset_00006', 'A2ARDataset_00007', 'A2ARDataset_00008',\n       'A2ARDataset_00009',\n       ...\n       'A2ARDataset_39858', 'A2ARDataset_40026', 'A2ARDataset_40029',\n       'A2ARDataset_40031', 'A2ARDataset_40033', 'A2ARDataset_40038',\n       'A2ARDataset_40041', 'A2ARDataset_40273', 'A2ARDataset_40410',\n       'A2ARDataset_40626'],\n      dtype='object', length=10361)] are in the [index]"

In [98]:
X3_all.df

,QSPRID,Y,Drug,Y_original
0,A2ARDataset_00000,False,O=[N+]([O-])c1ccccc1SSc1ccccc1[N+](=O)[O-],0
1,A2ARDataset_00001,False,CC(C)(CCC(=O)O)CCC(=O)O,0
2,A2ARDataset_00002,False,CN(C)C1=[S+][Zn-2]2(S1)SC(N(C)C)=[S+]2,0
3,A2ARDataset_00003,False,CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(C(=O)NC(CCC(=O)...,0
4,A2ARDataset_00004,False,[N-]=[N+]=CC(=O)OCC(N)C(=O)O,0
...,...,...,...,...
10356,A2ARDataset_40038,False,COc1ccc2nc3ccc(OC)cc3c([S+]([O-])Cc3ccccc3)c2c1,0
10357,A2ARDataset_40041,False,COc1ccc2nc3ccc(OC)cc3c([S+]([O-])Cc3ccc([N+](=...,0
10358,A2ARDataset_40273,False,O=C1Sc2ccccc2C(=O)N2C[S+]([O-])CC12,0
10359,A2ARDataset_40410,False,Cc1cn(COCC[S+]([O-])c2ccccc2)c(=O)[nH]c1=O,0
10360,A2ARDataset_40626,False,Cc1cn(COCCC[S+]([O-])c2ccccc2)c(=O)[nH]c1=O,0